### PR TITLE
fix the navbar responsiveness in mobile

### PR DESCRIPTION
**Pull request by adityalaxkar123**
# fix the navar responsiveness in mobile

### CODE REVIEW

**Review by thakuratul2 — APPROVED** [review]
@adityalaxkar123 Approved

**Comment by Charul00** [comment]
can i work on this

**Comment by adityalaxkar123** [comment]
My issue no. Is #24

**Comment by thakuratul2** [comment]
@Charul00 already merged

**Comment by adityalaxkar123** [comment]
Close the issue #24 @thakuratul2

**Pull request merged**
