### PR TITLE
Add Zoom-In Feature for Product Images

### PR DESCRIPTION
**Pull request by Paniv45**
This pull request introduces a zoom-in feature for product images in the ScrollMe e-commerce website. The changes enhance the user experience by allowing customers to view product details more closely, helping them make informed purchase decisions.

Changes Made:
Modified the src/pages/Product.jsx file to implement the zoom-in functionality on product images.
Ensured that the zoom feature is user-friendly and does not disrupt the overall layout of the product page.
Related Issues:
None at the moment, but this feature aims to improve usability and visual appeal.
Please review the changes and let me know if any modifications are needed or if you have any questions!
Screenshot 2024-10-16 171600

### CODE REVIEW

**Comment by Paniv45** [comment]
Kindly accept my 2nd commit "zoom-in feature for product images" to enable the feature for the site.

**Comment by Paniv45** [comment]
Kindly Approve it

**Comment by saurabhbakolia** [comment]
Hey @Paniv45, 

It is not looking good. 
can you come up with something creative?

**Comment by Paniv45** [comment]
What else do you want? Any suggestions? And by the way this image only comes up when someone click on the product from the product page otherwise it will show the normal product page with price colour and normal size image .

**Comment by Paniv45** [comment]
Kindly give suggestions if you have any.

**Comment by Paniv45** [comment]
I had updated 360 degree rotation view for the product image kindly review it and if you have any suggestion kindly tell me.

**Comment by saurabhbakolia** [comment]
> I had updated 360 degree rotation view for the product image kindly review it and if you have any suggestion kindly tell me.

Hey @Paniv45, 
Kindly share the video if you have made new changes. 
and regarding the suggestion, you can check `amazon `or `myntra `website. We can add something like that.

**Comment by Paniv45** [comment]
I had update the pull request, you can view that 360 degree rotation by
viewing the pull request again .
Or if u can share your WhatsApp contact than I can send you the video.

**Comment by saurabhbakolia** [comment]
Hey @Paniv45 , 
I think the previous one was way better than this rotation one. 

Also, can you make it like this? 
image

**Comment by Paniv45** [comment]
Done with the suitable changes and made a pull request from the name "Finalization of zoom in feature" .

**Comment by saurabhbakolia** [comment]
Hey @Paniv45, 
You again made the same mistake. Create a pr to `develop` branch.

**Pull request closed without merging**
