### PR TITLE
Added wishlist page and functionality to cart page

### LINKED ISSUE #95: Adding wishlist page and functionality to the cart
# Issue Report

## Description

Cart:
Allowing users to add and remove items from cart 
Aslo quantity  maintaining quatity of an item
Aslo updating the checkout amout in cart

Wishlist 
Adding and removing items to wishlist

## Steps to Reproduce the Issue

To assist us in understanding and resolving the issue, please outline the steps you took that led to the problem:

1. **Action 1:** Maintiaining cart using context api
2. **Action 2:** adding another page wishlist to the routes in frontend
3. **Action 3:** Adding and removing items dynamically

## Expected Behavior
A functional cart and wishlist pages

## Actual Behavior

Cart is not functional 
No wishlist is present

## Screenshots (if applicable)
NO wishlist page is present
image

@thakuratul2  @saurabhbakolia  assign this to me

### PR DESCRIPTION
**Pull request by govindumeesala**
## Related Issue

Fixes #95 

### **Description:**
This pull request introduces the following key features:

1. **Wishlist Functionality:**
   - Implemented a new **Wishlist page** where users can view all products they've added to their wishlist.
   - Users can **remove products** from the wishlist directly from the Wishlist page.
   - The wishlist data is stored in the **Redux store** using `wishlistSlice`.
   - Products are rendered dynamically on the Wishlist page by filtering `allProducts` based on the product IDs stored in the `wishlistSlice`.
   - A button for adding products to the wishlist has been integrated into the product display component (`Product.jsx`), using the **FavoriteBorderOutlined** icon.
  
2. **Cart Functionality:**
   - Added functionality to the **Add to Cart** button in the product component, enabling users to add products to their cart.
   - The cart state is managed via **Redux**, and cart items are stored using `cartSlice`.
   - Users can now add items to their cart, and an alert confirms when the item has been successfully added.

### **Files Modified:**
- **`store/Slices/WishlistSlice.js`**: Created to handle wishlist-related actions (add and remove items from the wishlist).
- **`components/Product.jsx`**: 
   - Added a "Favorite" icon that allows users to add items to the wishlist.
   - Integrated the "Add to Cart" button functionality.
- **`components/Wishlist.jsx`**: Created a new Wishlist component to display the wishlisted products with a "Remove from Wishlist" button.
- **`data.js`**: Contains all product data, used to dynamically render products in both the Wishlist and Cart.
  
### **Additional Changes:**
- Configured the Redux store (`store.js`) to handle both **cart** and **wishlist** reducers.
- Added a new route to render the **Wishlist** page within the app.

### **How to Test:**
1. Navigate to any product page and use the **Favorite icon** to add items to the wishlist.
2. Visit the **Wishlist page** (`/wishlist`) to view the added products.
3. Remove items from the wishlist using the **Remove from Wishlist** button.
4. Use the **Cart icon** to add items to the cart, and confirm the addition with the success alert.

## Changes Made

- [x] Briefly describe the changes you made. Include any relevant information.

## Checklist

- [x] I have tested my code and it works as expected.
- [x] I have added/updated documentation where necessary.
- [x] I have included tests for new features.
- [x] I have followed the project's coding standards.

### **Screenshots:**
image
image

@thakuratul2 check once please

### CODE REVIEW

**Comment by saurabhbakolia** [comment]
Hey @govindumeesala,
I really like the design of the wishlist page! However, I have some ideas for improvements to the wishlist card. I've shared a screenshot for you to look over. Let me know what you think!
image


> Don't forge to take pull.  

Thanks,

**Comment by govindumeesala** [comment]
@saurabhbakolia  ok I will do it

**Comment by govindumeesala** [comment]
@saurabhbakolia Heyy made requested changes

image

please check once

**Comment by govindumeesala** [comment]
@saurabhbakolia  Heyy I have resolved conflicts. Please consider merging this pr

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia Heyy I have resolved conflicts. Please consider merging this pr

doing it now!

**Comment by govindumeesala** [comment]
> > @saurabhbakolia Heyy I have resolved conflicts. Please consider merging this pr
> 
> doing it now!

okay

**Comment by govindumeesala** [comment]
@saurabhbakolia please add labels to it. It would be helpful for me.

Thank you

**Comment by govindumeesala** [comment]
@saurabhbakolia  please add level and gssoc labels to it. It would be helpful for me. Kindly add gssoc-ext and level
Label to it.

**Pull request merged**
