### PR TITLE
slider responsiveness

### PR DESCRIPTION
**Pull request by adityalaxkar123**
# now slider is responsive for mobile,macs and ipad device users.

### CODE REVIEW

**Comment by adityalaxkar123** [comment]
review this

**Comment by adityalaxkar123** [comment]
My issue no. #132

**Comment by adityalaxkar123** [comment]
Review this @thakuratul2 
@saurabhbakolia

**Comment by thakuratul2** [comment]
@adityalaxkar123 please create the PR to develop branch

**Pull request closed without merging**
