### PR TITLE
 Added multiple language support to ScrollMe

### PR DESCRIPTION
**Pull request by IkkiOcean**
**Title:** Add multiple language support

## Description

This pull request implements multiple language support in the application by integrating the Google Translate widget. Users can now switch between languages seamlessly, improving accessibility and user experience for a diverse audience.

## Related Issue

- Closes : #228 

## Changes Made

- Added a Google Translate widget to the navigation bar for language selection.
- Removed the previous language tag and replaced it with the GTranslate wrapper.
- Updated styles to ensure proper display and responsiveness of the language selection feature.

## Checklist

- [x] I have tested my code and it works as expected.
- [ ] I have added/updated documentation where necessary.
- [ ] I have included tests for new features.
- [x] I have followed the project's coding standards.

## Screenshots (if applicable)

https://github.com/user-attachments/assets/073b9026-9c2f-4e6b-918c-9ed4cd21f0d7

### CODE REVIEW

**Comment by saurabhbakolia** [comment]
Hey @IkkiOcean, 
This feature is cool. But create a PR to `develop` branch and add this language Modal to the `Navbar`, What do you think?.

**Comment by saurabhbakolia** [comment]
Closing this PR as it does not meet the requirements.

**Comment by IkkiOcean** [comment]
@saurabhbakolia we cant put it in navbar as the component is a google widget and offers very limited customisation. putting it in navbar will interfere with the other components of navbar as the dropdown opens up. that's why I chose to put it at the bottom left as it will be easily accessible to the users who lacks the knowledge of language display on the page to switch

**Comment by IkkiOcean** [comment]
should I PR again then?

**Pull request closed without merging**
