### PR TITLE
Add font-awesome stylesheet and create ComingSoon page and some more Fucntionality…

### PR DESCRIPTION
**Pull request by coder-writes**
This pull request introduces a new "Coming Soon" page and updates various components to integrate this new feature. The most important changes include adding the "Coming Soon" page, updating the footer links which will now redirect to the coming soon page(image attached), and enhancing the newsletter component with state management and user interaction.

### New Feature: Coming Soon Page

* [`src/pages/ComingSoon.jsx`](diffhunk://#diff-12e6c26ac3957c0a0bbf1ccb1f7d8b501acc1ab9d940dae4843fba8ada781d9fR1-R110): Created a new "Coming Soon" page with styled components and user notification functionality.
* [`src/App.js`](diffhunk://#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67R12): Imported the `ComingSoon` component and added a new route for it. [[1]](diffhunk://#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67R12) [[2]](diffhunk://#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67R50)

### Updates to Existing Components

* [`src/components/Footer.jsx`](diffhunk://#diff-618acf142786bf7414152d4982d3d647b5ca1f96edaed7385ba0f17b46741b65L126-R149): Updated footer links to point to the "Coming Soon" page.
* [`src/components/Newsletter.jsx`](diffhunk://#diff-d5dcfe393f1a96248175d5e3a07af83bc27a88ff07ae16c0bc332ab59a4483e3R4): Added state management for the email input and a notification handler. [[1]](diffhunk://#diff-d5dcfe393f1a96248175d5e3a07af83bc27a88ff07ae16c0bc332ab59a4483e3R4) [[2]](diffhunk://#diff-d5dcfe393f1a96248175d5e3a07af83bc27a88ff07ae16c0bc332ab59a4483e3R47-R72)

### External Resources

* [`public/index.html`](diffhunk://#diff-c2cc24bc9001b11b6add48a4cd8f893d5d6c6e4d1bd254158bd14ab997f552cdR18): Added a link to the Font Awesome stylesheet for social media icons.

ScreenShot

Screenshot 2024-10-22 071138
Screenshot 2024-10-22 144204
Screenshot 2024-10-22 144214

When we Use The NewsLetter Section then we get the notification.

Screenshot 2024-10-22 144323

@saurabhbakolia Hey please review the Changes and please share if any further changes needed. and if not please merge this PR with suitable level and tags.

### CODE REVIEW

**Comment by coder-writes** [comment]
@saurabhbakolia Please give the review and merge the PR.

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia Please give the review and merge the PR.

I have added my review them.

**Comment by coder-writes** [comment]
> > @saurabhbakolia Please give the review and merge the PR.
> 
> I have added my review them.

I did'nt get  it. Can You  please explain what you want to say ?

**Comment by saurabhbakolia** [comment]
> > > @saurabhbakolia Please give the review and merge the PR.
> > 
> > 
> > I have added my review them.
> 
> I did'nt get it. Can You please explain what you want to say ?

Don't use, font-awesome icons, we are using Material UI Icons.

**Comment by coder-writes** [comment]
> > > > @saurabhbakolia Please give the review and merge the PR.
> > > 
> > > 
> > > I have added my review them.
> > 
> > 
> > I did'nt get it. Can You please explain what you want to say ?
> 
> Don't use, font-awesome icons, we are using Material UI Icons.

I changed the index .html file and comingSoon.jsx and this time I used the Material.UI Icons.

**Comment by coder-writes** [comment]
Hey @saurabhbakolia Please merge the PR if no any further changes needed

**Comment by saurabhbakolia** [comment]
> Hey @saurabhbakolia Please merge the PR if no any further changes needed

Okay I will merge, it give me some time.

**Comment by coder-writes** [comment]
@saurabhbakolia please add the labels of GSSoc Extd and hacktoberfest and suitable level to be this PR be considered.

**Comment by coder-writes** [comment]
hey @saurabhbakolia please assign suitable labels to reflect my points in the leaderboard as one of the PR merged after your PR is reflected in the leaderboard.

**Pull request merged**
