### PR TITLE
Updated signup UI

### LINKED ISSUE #216: SignUp page UI can be modified.
# Issue Report

## Title

UI of SignUp page can be modified.

## Description

The SignUp UI is not looking good.
The boxes of firstname, lastname, pasword, email etc. are not visible which gives it a page like look.
And Add eye icons on password and confirm password.
Add hover effects on create Account and SignIn with Google.

## Expected Behavior

Add boxes for the firstname,lastname
Add hover effects on Create and SignIn with Google.
Add eye icons for password visibility in password and confirm password.

## Screenshots (if applicable)
scrollme

## Additional Context

Kindly assign this to me under GSSOC'24-extd and Hacktoberfest.

---

### PR DESCRIPTION
**Pull request by Priyanshu1035**
**Title:**  Updated SignUp UI

## Description

Add borders for the input boxes and also add hover effects on the Signup using google and create button.

## Related Issue

`Fixes #216 `
Fixes #216

## Changes Made
Add borders for the input boxes and also add hover effects on the Signup using google and create button.

## Checklist

- [ ] I have tested my code and it works as expected.
- [ ] I have added/updated documentation where necessary.
- [ ] I have included tests for new features.
- [ ] I have followed the project's coding standards.

## Screenshots (if applicable)
Scroll_me2

---

### CODE REVIEW

**Comment by saurabhbakolia** [comment]
Hey @Priyanshu1035, 
it looks cool, but can you also arrange the `google sign` button, it looks awful. Also, we have to change the `login` accordingly.

**Comment by Priyanshu1035** [comment]
Sure, Why not? 
But Can I do it by creating a new issue ?
It will also help me.

**Comment by saurabhbakolia** [comment]
Yes go ahead!

**Comment by Priyanshu1035** [comment]
Kindly merge it.

**Comment by saurabhbakolia** [comment]
Hey @Priyanshu1035, 
So that you know, this change is not required.

Closing this PR.

**Pull request closed without merging**
