### PR TITLE
Added payment getway

### LINKED ISSUE #185: [Improvement]: Adding Payment gateway usign
# Feature Update

## Title
Payment Getway

## Description
I will add Payment getaway for the user so that when user will click on payment icon on footer section the user will redirect to payment page 

## Steps to Implement this feature
1. I will send user data from frontend to backend calling payment getway.
2. Verify the data sent from frontend and authentication.
3. Hashing and adding salt and key to data to create payload.
4. Creating Payload for API call.
5. calling the Payment Getway API 
6. Send response to the user about payment failed or success

## Expected Behavior
The user should able to make payment 

## Actual Behavior
Static page the user is not able to make payment

## Screenshots
image

@thakuratul2 @saurabhbakolia I'll be using testing getaway later you can change it to your original payment gateway.

### PR DESCRIPTION
**Pull request by Amarjha01**
## Title: 
Added payment Gateway 

## Description

added payment gateway in cart.jsx

## Related Issue #185 
Fixes : #185 

## Changes Made

- Added a new controller in the backend for Payment Gateway
- modified cart.jsx 

## Checklist

- [X] I have tested my code and it works as expected.
- [X] I have followed the project's coding standards.

## Video 

https://github.com/user-attachments/assets/d5b86f2d-9205-4d11-aafe-ea3c347b48f8

### CODE REVIEW

**Comment by Amarjha01** [comment]
@saurabhbakolia  @thakuratul2  okay sir as you said I Leave the product code as it is I just implemented payment gateway when user will click on checkout it will redirect to phonepay payment gateway to make testing payment it can be further modify to align with product and you can replace credentials with original if needed now please verify and merge this.

**Comment by thakuratul2** [comment]
@Amarjha01 oky

**Comment by Amarjha01** [comment]
@thakuratul2 @saurabhbakolia kindly verify this PR.

**Comment by saurabhbakolia** [comment]
Hey @Amarjha01, 
I missed it, can you create a pr to `develop` branch ?

**Comment by Amarjha01** [comment]
> Hey @Amarjha01, I missed it, can you create a pr to `develop` branch ?

did it sir.

**Comment by saurabhbakolia** [comment]
Closing this PR as doesn't meet the PR requirements.

**Pull request closed without merging**
