### PR TITLE
Improve login page design

### LINKED ISSUE #144: Add: Add product search functionalityto show products
## Description
The search functionality on our e-commerce platform is a vital tool that directly impacts the shopping experience for our users. By improving this feature, we can help users find products more efficiently and enhance overall satisfaction. Key benefits include faster product discovery, personalized results, advanced filtering options, and improved user engagement.

## Steps to Implement the Search Functionality

1. **Develop Autocomplete Feature:** Implement real-time suggestions as users type, showing popular searches and relevant products.

2. **Integrate Search Algorithm:** Optimize the search algorithm to prioritize relevant results and enhance user experience

## Expected Behavior

When users input a keyword into the search bar, they should see a list of relevant products matching the search term, including accurate filtering and sorting options.

### PR DESCRIPTION
**Pull request by RajukrRaja**
Pull Request Template
Title: Improve Password Validation Logic

Description
This pull request enhances the password validation logic in the user registration form to enforce stronger password requirements. The improvements include:

Updated Validation Criteria:

Minimum of 8 characters.
At least one uppercase letter.
At least one lowercase letter.
At least one digit.
At least one special character (e.g., !@#$%^&*).
Password Strength Indicator:

Integrated react-password-strength-bar to provide real-time feedback on password strength as users type.
User Feedback:

Replaced alert messages with Chakra UI's toast notifications for a more polished and user-friendly experience.
Loader Enhancement:

Improved the loader overlay to cover the entire viewport, ensuring users are aware of ongoing processes during form submission.
Related Issue
Fixes #144

Changes Made
Password Validation:

Updated the regular expression in the validateForm function to enforce the new password criteria.
Enhanced the validateForm function to include checks for uppercase letters, lowercase letters, digits, and special characters.
Password Strength Indicator:

Installed and integrated react-password-strength-bar to visually indicate password strength.
Added state management for password to dynamically update the strength bar.
User Feedback:

Implemented Chakra UI's useToast for displaying success and error messages instead of using alert.
Provided specific feedback messages to guide users in creating strong passwords.
Loader Overlay:

Modified the loader overlay's styling to ensure it effectively covers the entire viewport during form submission.
Code Refactoring:

Organized state management for form data to improve readability and maintainability.
Enhanced form accessibility by adding aria-labels to input fields.
Checklist
 I have tested my code and it works as expected.
 I have added/updated documentation where necessary.
 I have included tests for new features.
 I have followed the project's coding standards.
Screenshots (if applicable)
Before Improvements

Description: The password validation only checked for minimum length and basic character inclusion, leading to weak passwords.

After Improvements

Description: Enhanced password validation ensures stronger security by enforcing a mix of character types and providing real-time strength feedback.

Notes for Reviewers:

Please verify that the password strength indicator accurately reflects the strength based on the defined criteria.
Ensure that the toast notifications appear appropriately for both successful registrations and validation errors.
Test the loader overlay to confirm it functions correctly during form submissions without causing any UI glitches.
Additional Information:

Dependencies Added:
react-password-strength-bar: For the password strength indicator.
@chakra-ui/react, @emotion/react, @emotion/styled, framer-motion: For toast notifications and UI enhancements.

### CODE REVIEW

**Review by RajukrRaja — COMMENTED** [review]
Review Summary: The improvements to the login page design look promising! Here are a few observations and suggestions to enhance the changes further:

UI Enhancements:

The overall layout looks more modern, but we could explore improving the mobile responsiveness further (especially for smaller devices like phones).
Consider adding some padding around form fields for better spacing and readability.
Code Optimization:

The imports in Login.jsx are well organized, but check if we can refactor repeated logic into a custom hook or a reusable component for cleaner code.
Ensure that error handling is consistent and provides meaningful feedback to the user, especially for invalid login attempts.
File Size Optimization:

Review package-lock.json for any redundant dependencies added during the design changes, as it seems to have a significant size change. Verify if we can optimize this.
Testing:

If not already done, consider adding unit or integration tests for the UI changes, ensuring no regressions occur due to the new design.
Overall, great work! Just a few tweaks and considerations can make the design and code even more polished.

**Comment by RajukrRaja** [comment]
Great improvements on the login page! A few suggestions:

Mobile Responsiveness: Improve spacing and layout for better usability on smaller screens.
Code Refactor: Consider consolidating repeated logic into reusable components or hooks.
Package Review: The package-lock.json size increased significantly—double-check for unnecessary dependencies.
Testing: Add or update tests to cover these design changes.
Overall, fantastic work!

**Comment by thakuratul2** [comment]
@RajukrRaja can you provide video link

**Comment by thakuratul2** [comment]
@RajukrRaja and create the pull request to develop branch

**Pull request closed without merging**
