### PR TITLE
Added logout function to the website

### LINKED ISSUE #102: Bug NO log out button after logging in
# Issue Report

## Description

No log out button present in the navbar once user logged in 

## Steps to Reproduce the Issue

To assist us in understanding and resolving the issue, please outline the steps you took that led to the problem:

1. **Action 1:** log in to the website 
2. **Action 2:** You will see no log out button

## Expected Behavior

Log out button should be in navbar to allow users to log out

## Actual Behavior

No log out option available

## Screenshots (if applicable)

image

@saurabhbakolia  @thakuratul2  assign this to me

### PR DESCRIPTION
**Pull request by govindumeesala**
# Pull Request Template

**Title:** Logout functionality

## Description

Added logout functionality
Updated both frontend and backend

## Related Issue

`Fixes #102 

## Changes Made

- [x] Briefly describe the changes you made. Include any relevant information.

## Checklist

- [x] I have tested my code and it works as expected.
- [x] I have added/updated documentation where necessary.
- [x] I have included tests for new features.
- [x] I have followed the project's coding standards.

## Screenshots (if applicable)
image
image
image

@saurabhbakolia @thakuratul2  added logout functionality

### CODE REVIEW

**Comment by govindumeesala** [comment]
@thakuratul2 @saurabhbakolia  please consider adding level3 or level2 label to the pr.
I worked really hard to implement and come up with the logic.

**Comment by saurabhbakolia** [comment]
Hey 
@govindumeesala 
can you create a menu like this?
image
A dropdown will open when the user clicks on the profile menu. 
image


Make sure you create a PR to `develop` the branch. If you have any other better idea, please suggest.

**Comment by govindumeesala** [comment]
> Hey @govindumeesala can you create a menu like this? image A dropdown will open when the user clicks on the profile menu. image
> 
> Make sure you create a PR to `develop` the branch. If you have any other better idea, please suggest.

Sure @saurabhbakolia  
Can you please consider merging this pr.
I will raise new issue profile pop-up and work on it. 
If you check this once and merge , it means a lot to me.

**Comment by thakuratul2** [comment]
@govindumeesala you create new issue when we review it will be merge. So meanwhile you start working

**Comment by govindumeesala** [comment]
> @govindumeesala you create new issue when we review it will be merge. So meanwhile you start working

ok thank you

**Comment by thakuratul2** [comment]
@govindumeesala why this branch having code of contact us page?

**Comment by govindumeesala** [comment]
> @govindumeesala why this branch having code of contact us page?

I previously worked on contact us page and faq .
I thought after merging the that pr. This will be merged, so I created a new branch (bugLogout) #125  from that branch (featReachoutUS) #90 
@thakuratul2  you said all fine with that pr #90 , but it didnt get merged yet.

**Comment by thakuratul2** [comment]
@govindumeesala no why you create the branch from that one you need to create new branch always from develop if they updated or not due to this your previous commits also comes here we cannot be merge this

**Comment by govindumeesala** [comment]
@thakuratul2 
From next time I will definitely do it from develop branch. 
please check once, There are no conflicts. All working fine. 
First merge #90 
Then merge #125 
I will for sure create a branch from develop from next time 
Please consider once, since, everything is working fine. 

Thankyou

**Comment by thakuratul2** [comment]
@govindumeesala so please close the your last pr then I will merge it

**Review by thakuratul2 — APPROVED** [review]
@govindumeesala next time please always create branch from the develop

**Pull request merged**
