### PR TITLE
Updated README.md with pull request instructions

### PR DESCRIPTION
**Pull request by Charul00**
# Pull Request Section

## Description
This pull request aims to add a dedicated section for pull requests in the README file, ensuring it is included in the table of contents. The link to this section will be made clickable for easy navigation.

## Related Issue
Fixes: #18

## Changes Made
- Added a "Pull Request" section in the `README.md` file.
- Ensured that the links within the README are clickable, enhancing user experience and accessibility.

## Checklist
- [ ] I have tested my code and it works as expected.
- [ ] I have added/updated documentation where necessary.
- [ ] I have included tests for new features.
- [ ] I have followed the project's coding standards.

## Screenshots (if applicable)
Add any relevant screenshots or examples that help illustrate your changes.
Screenshot 2024-10-02 123849
Screenshot 2024-10-02 123834

### CODE REVIEW

**Comment by thakuratul2** [comment]
@Charul00 please make the proper PR request and add issue number

**Comment by Charul00** [comment]
> @Charul00 please make the proper PR request and add issue number

ok

**Comment by Charul00** [comment]
# Pull Request Section

## Title: Pull Request is Missing from the README.md Table of Contents

## Description
This pull request aims to add a dedicated section for pull requests in the README file, ensuring it is included in the table of contents. The link to this section will be made clickable for easy navigation.

## Related Issue
Fixes: #18

## Changes Made
- Added a "Pull Request" section in the `README.md` file.
- Ensured that the links within the README are clickable, enhancing user experience and accessibility.

## Checklist
- [ ] I have tested my code and it works as expected.
- [ ] I have added/updated documentation where necessary.
- [ ] I have included tests for new features.
- [ ] I have followed the project's coding standards.

## Screenshots (if applicable)
Screenshot 2024-10-02 123849
Screenshot 2024-10-02 123834

**Comment by Charul00** [comment]
> @Charul00 please make the proper PR request and add issue number

yeah i made this check please

**Comment by thakuratul2** [comment]
@Charul00 we have already a md file of Pull request only you want to add the path to access it

**Comment by Charul00** [comment]
> @Charul00 we have already a md file of Pull request only you want to add the path to access it

do i have to add path of my pr ?

**Comment by thakuratul2** [comment]
@Charul00 please join this link for better communication https://discord.gg/w4nKprr5

**Comment by thakuratul2** [comment]
@Charul00 your code is having conflicts

**Comment by Charul00** [comment]
> @Charul00 your code is having conflicts

ok
i resolve asap

**Pull request closed without merging**
