### PR TITLE
added recent updates/blogs functionality

### PR DESCRIPTION
**Pull request by Hustler004**
# Pull Request Template

**Title: Added recent updates section**

## Description

Hi! thank you for assigning me the issue, I've successfully implemented the recent updates section in the home page, there was no navbar so i couldn't add any button referring to the page but I anyways it is visible on the home screen. Also it is completely dynamic in terms of screen size, all the components are styled to behave properly with changing screen sizes supporting large array of users. 

## Related Issue

Link to the issue that this pull request addresses `Fixes #[183]`

## Changes Made

- [ Added some stock photos in public folder, added 2 components Blogs.jsx and Blog.jsx, Blogs.jsx is imported in Home.jsx file which stores the information regarding blogs and uses BlogCard from Blog.jsx for further implementation. ] 

## Checklist

- [x] I have tested my code and it works as expected.
- [x] I have added/updated documentation where necessary.
- [x] I have followed the project's coding standards.

## Screenshots (if applicable)

image

image

---

### CODE REVIEW

**Comment by Hustler004** [comment]
Hi @thakuratul2, It's been three days since I raised this PR, and I would really appreciate some feedback from your side.

**Comment by saurabhbakolia** [comment]
Hey @Hustler004, 

Can you make it a little creative on the same side make it as minimal as possible?
Before that take pull from `develop` branch.

**Comment by thakuratul2** [comment]
@Hustler004 i am closing this issue please create the PR request to the develop branch

**Comment by Hustler004** [comment]
I'll surely do, do you have anything specific in mind, I was thinking like a horizontally scrollable image gallery kind of thing, with a little bit of css we can work it out with site's aesthetics!

**Pull request closed without merging**
