### PR TITLE
Add PR checks workflow for pull requests

### PR DESCRIPTION
**Pull request by Rizvi-Faiz**
# Pull Request Template

**Title:** Add GitHub Actions Workflow for PR Checks

## Description

This pull request adds a GitHub Actions workflow that automates checks for pull requests (PRs). The workflow is triggered when a PR is opened, edited, or reopened. It performs the following tasks to ensure the quality of the pull request:

- **Checkout Code**: Retrieves the latest version of the code from the repository.
- **Set Up Node.js Environment**: Installs Node.js version 16 for running commands.
- **Install Dependencies**: Runs `npm install` to install all necessary project dependencies.
- **Run Tests**: Executes unit tests via `npm test` to ensure no functionality is broken.
- **Lint Code**: Optionally checks code formatting and style via `npm run lint`.
- **Build Project**: Builds the project to ensure that the build passes successfully.
- **Security Checks**: Optionally performs security audits on dependencies via `npm audit`.
- **Static Code Analysis**: (Optional) Runs static analysis tools (like ESLint) to detect potential issues.
- **Post Notifications**: Provides success or failure notifications based on the result of the checks.

## Related Issue

Fixes #15 

## Changes Made

- Added `pr-check.yml` under `.github/workflows` directory.
- Configured the workflow to run on PRs when they are opened, edited, or reopened.
- Set up Node.js environment, dependency installation, linting, testing, and build steps.
- Optional security checks and static code analysis included in the workflow.

## Checklist

- [x] I have tested my code and it works as expected.
- [ ] I have added/updated documentation where necessary.
- [x] I have included tests for new features.
- [x] I have followed the project's coding standards.

## Screenshots (if applicable)

image

## Reviewers
@thakuratul2

### CODE REVIEW

**Comment by Rizvi-Faiz** [comment]
@thakuratul2 Sir could you review it

**Comment by thakuratul2** [comment]
@Rizvi-Faiz oky i will review it and meanwhile find new issue

**Review by thakuratul2 — APPROVED** [review]
@Rizvi-Faiz Approved

**Comment by Rizvi-Faiz** [comment]
@thakuratul2 please add the levels in this pr and the gssoc-ext and hactoberfest
and also that you assigned me cause if you dont add they will not count towards my points
can you please add them

**Comment by Rizvi-Faiz** [comment]
@thakuratul2  @saurabhbakolia  can you please add the labels here the issue #15

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia SIRR CAN YOU PLEASE ADD THE LABELS TO THIS PR AND ALSO ASSIGN THIS PR TO ME AND THIS ISSUE IS LEVEL 3
SO PLEASE ADD THE LEVEL 3 LABEL AS I FIXED ISSUE NUMBER #15 .
I AM NOT GETTING POINTS FOR THIS PR BECAUSE YOU DID NOT ASSIGN OR GIVE LABELS .
CAN YOU PLEASE DO IT.

**Pull request merged**
