### PR TITLE
[BUG] #36 added favicon icon

### LINKED ISSUE #36: Bug: favicon icon
## Title
favicon icon

## Description

There is no favicon icon for the website. It needs to be created and updated in code.

## Steps to Reproduce the Issue

1. Desigining favicon icon which matches the project type.
2. Adding favicon icon to public folder and URI in index.html file.

### PR DESCRIPTION
**Pull request by Amarjha01**
### 🛠️ Fixes Issue #36 
closes #36 

**Title:** [A short summary of the pull request]
Added favicon icon
## Description
Added a favicon icon

## Screenshots (if applicable)

scrollme-removebg-preview

### CODE REVIEW

**Comment by saurabhbakolia** [comment]
Hey @Amarjha01 
can you create a new logo, like amazon? 
and also use the first character of scrollme? 
What do you think about this ?

**Comment by Amarjha01** [comment]
> Hey @Amarjha01 can you create a new logo, like amazon? and also use the first character of scrollme? What do you think about this ?

This sounds good. Off course I'll create some awesome favicon icon like amazon .

image

**Comment by Amarjha01** [comment]
scrollme

scrollme-preview

@saurabhbakolia sir is this okay now ?

**Comment by vikas83pal** [comment]
@saurabhbakolia  I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.


i can add the logo some want like amazon sating with s with more interactive

Thanks so much!

**Comment by thakuratul2** [comment]
@Amarjha01 can you provide the video link

**Comment by Amarjha01** [comment]
> @Amarjha01 can you provide the video link

Video link of what sir ?

**Comment by thakuratul2** [comment]
@Amarjha01 favicon icon is added showing proper or not

**Comment by Amarjha01** [comment]
https://github.com/user-attachments/assets/b81e66b6-3876-4394-a352-8cf2390a0777

@thakuratul2 avoid the that's case sensitive error. I will only push favicon icon

**Comment by Amarjha01** [comment]
@saurabhbakolia @thakuratul2  Sir whenever I push the corrected path vercel fails to deploy. I can't view details of why Vercel was unable to deploy to solve the error.

**Comment by saurabhbakolia** [comment]
Hey @Amarjha01, 

I think the logo made is okay, but let's give it a try @vikas83pal. 

@vikas83pal can you create an attractive logo with a minimalistic design? 
@vikas83pal  assigned!

Now that we've clarified the requirements, I’d like both of you to discuss and collaborate on creating a new logo. Please share your ideas and mockups once you’ve come to a consensus. Looking forward to seeing your creative designs!

**Comment by Amarjha01** [comment]
> Hey @Amarjha01,
> 
> I think the logo made is okay, but let's give it a try @vikas83pal.
> 
> @vikas83pal can you create an attractive logo with a minimalistic design? @vikas83pal assigned!
> 
> Now that we've clarified the requirements, I’d like both of you to discuss and collaborate on creating a new logo. Please share your ideas and mockups once you’ve come to a consensus. Looking forward to seeing your creative designs!

Till now I was only working on creating favicon icon but now as you mentioned logo I will look forward. @vikas83pal https://discord.com/invite/wG8CcwKN please join discord

**Comment by thakuratul2** [comment]
@vikas83pal branch having conflicts

**Comment by vikas83pal** [comment]
@thakuratul2 in my repo it is working very fine

**Comment by vikas83pal** [comment]
> @vikas83pal branch having conflicts


merge with bug-99

**Comment by vikas83pal** [comment]
@thakuratul2 please reopen the issue
and add label and tags

**Pull request closed without merging**
