### PR TITLE
Toggle Product Images With Respect To Change In Color.

### LINKED ISSUE #94: [BUG] : Colour Of Product Is Not changing
# Issue Report

## Title
Colour of product Isn't changing.

## Description
Colour of product is not changing when user select different different colors.

## Steps to Reproduce the Issue
- change the image align to colour selected by user using state management.

## Expected Behavior
- Product Image should change when user select different different color.
- Image should be dynamic.

## Actual Behavior
The image of product is static and not changing when user select different colour.

## Video

https://github.com/user-attachments/assets/b6b39dcd-8e11-4126-b243-d0f362fc99ef

https://github.com/user-attachments/assets/e242dbe1-1c8a-484f-8eb3-df4f2156a80c

@thakuratul2 @saurabhbakolia  sir I would like to work on this issue.

### PR DESCRIPTION
**Pull request by Amarjha01**
### 🛠️ Fixes Issue #94
Fixes #94 

### 👨‍💻 Description
Added A Feature To Toggle Product Images With Respect To Change In Color And Deleted Some Unused Images.

### 📄 Type of Change
- Deleted Unused Images
- Added feature to toggle images 

### 📷 Video

https://github.com/user-attachments/assets/ecc4db5b-5c3e-4c8e-85c3-906edb7046a0

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.

### CODE REVIEW

**Comment by Amarjha01** [comment]
@thakuratul2  @saurabhbakolia Sir I've raised PR could you please review this .

**Comment by Amarjha01** [comment]
@thakuratul2 @saurabhbakolia Sir I've noticed that someone pushed the .env file all credentials are open now. If you give permission I'll delete .env file and push update here.

**Comment by thakuratul2** [comment]
@Amarjha01 yes remove it

**Comment by thakuratul2** [comment]
@Amarjha01 your branch again having conflicts

**Comment by Amarjha01** [comment]
> @Amarjha01 your branch again having conflicts

yes sir I know but this time I'm not allowed to resolve it else I would have resolved it. 

image

**Comment by thakuratul2** [comment]
@Amarjha01 solve it via editor see what the conflicts here

**Comment by Amarjha01** [comment]
Option is disabled for me. I think I should receive last push. 

IMG_20241007_141311

**Comment by Amarjha01** [comment]
@thakuratul2 @saurabhbakolia Sir I've resolved the conflict you can now test and merge. Actually the conflict persist because I'm working on multiple issues on same repo.

Thank you for being supportive.

**Review by thakuratul2 — APPROVED** [review]
@Amarjha01 now i am approve this but next time please make the proper branch

**Comment by Amarjha01** [comment]
@thakuratul2  @saurabhbakolia  sir can you please assign me and add all the labels.  actually PR labels are only considered. 
gssoc-ext
hacktoberfest
hacktoberfest-accepted
level3

**Comment by Amarjha01** [comment]
> @Amarjha01 now i am approve this but next time please make the proper branch

 sure sir

**Comment by Amarjha01** [comment]
@thakuratul2 @saurabhbakolia   sir can you please assign me and add all the labels.  actually PR labels are only important.
gssoc-ext
hacktoberfest
hacktoberfest-accepted
level3

**Pull request merged**
