### PR TITLE
Added the Contributors Page in the website.

### LINKED ISSUE #182: Adding the contributors page to mention all the awersome people who have contributed to the website.
# Issue Report

## Title

Adding the contributors page to mention all the awersome people who have contributed to the website.

@saurabhbakolia Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this and create a amazing contributors page for the website to thank all the people who have contributed to this repo.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# Pull Request Template

Added the Contributors Page in the website.

## Description

Added the Contributors Page in the website.

## Related Issue

Fixes #182 

## Checklist

- [X] I have tested my code and it works as expected.
- [X] I have added/updated documentation where necessary.
- [X] I have included tests for new features.
- [X] I have followed the project's coding standards.

## Screenshots (if applicable)

image

image

@thakuratul2 @saurabhbakolia Please review this PR and merge it and before this merge #178 PR and assign this to me and put relevant labels like gssoc 2024 ext, hacktoberfest and level.

### CODE REVIEW

**Comment by thakuratul2** [comment]
@tarunkumar2005 where I access this page can you give the title of this page to access this

**Comment by tarunkumar2005** [comment]
@thakuratul2 /contributors

**Comment by thakuratul2** [comment]
@tarunkumar2005 mentioned in the website too then we can access by click on the header

**Comment by tarunkumar2005** [comment]
@thakuratul2 In the navbar or footer ??

**Comment by thakuratul2** [comment]
@tarunkumar2005 in the footer

**Comment by thakuratul2** [comment]
@tarunkumar2005 mentioned the mentor and project admin which are and mentioned contributor title in the new user

**Comment by tarunkumar2005** [comment]
@thakuratul2 Okay in api it is showing all of them same user only i will explecityly mention them as admins and mentors can you tell me who all are admins and mentors.

**Comment by thakuratul2** [comment]
@tarunkumar2005 only mention mentor as me and admin as @saurabhbakolia

**Comment by tarunkumar2005** [comment]
@thakuratul2 Now check it is updated

**Review by thakuratul2 — CHANGES_REQUESTED** [review]
@tarunkumar2005 can you provide the video

**Comment by tarunkumar2005** [comment]
https://github.com/user-attachments/assets/0b782c4a-6f8e-46d4-b70a-a400ffb66337

**Comment by thakuratul2** [comment]
@saurabhbakolia please merge it

**Comment by tarunkumar2005** [comment]
@thakuratul2 and @saurabhbakolia Pending PR (reminder)

**Comment by saurabhbakolia** [comment]
Hey @tarunkumar2005, 
I’m really impressed by the work you’ve done on the contribution page! However, could you please adjust the colors to align with the existing theme?

Thanks for your efforts!

**Comment by tarunkumar2005** [comment]
@saurabhbakolia Will do that and update the PR but don't take too much time to respond i know you might not be free and busy but like take some time like a hour or so to just go through the PRs and get them reviewed that is a request it's been open from last week. also check this one #178

**Comment by tarunkumar2005** [comment]
@saurabhbakolia Please check now i have updated the ui according to the theme. i hope you will give updates on it soon either you have any issue or merge it.

**Comment by tarunkumar2005** [comment]
@saurabhbakolia @thakuratul2 Bro it is took me so much time and contntinous updates with matching theme, responsive design and perfect page, you can at least put it level 3, i talked to sajay sir and he said for this much good design and perfection you need to give atleast level 3.

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia @thakuratul2 Bro it is took me so much time and contntinous updates with matching theme, responsive design and perfect page, you can at least put it level 3, i talked to sajay sir and he said for this much good design and perfection you need to give at least level 3.

who is this guy (Sanjay).

**Comment by tarunkumar2005** [comment]
@sanjay-kv

**Review by thakuratul2 — APPROVED** [review]
@tarunkumar2005 done

**Comment by sanjay-kv** [comment]
> saurabhbakolia

when did i say that?

dont pull my name on unnecessary PR. if there any issue with the labels project admin assign you. 

as a program manager i can help and fix any issue.

**Comment by tarunkumar2005** [comment]
@sanjay-kv you can check yourself how much efforts it takes to design the ui like this with proper functionality and I don't want to put the issue in the discussion every time so I directly said it soo I had raised a issue is discussion you can check that same thing was there.

**Comment by sanjay-kv** [comment]
okay got it.. @tarunkumar2005

**Pull request merged**
