### PR TITLE
 Update Footer for Enhanced Functionality and Modern Design

### PR DESCRIPTION
**Pull request by Rizvi-Faiz**
## Description

This pull request updates the footer of the ScrollMe web store to enhance its functionality, expand its content, modernize the visual design, and improve accessibility. The changes aim to provide users with a more informative, user-friendly experience while ensuring that the footer aligns with current UI standards.

## Related Issue

Fixed issue #14 

## Changes Made

- [x] Expanded the footer content by adding more links, including "Privacy Policy" and "Terms of Service."
- [x] Updated the visual design, including new color schemes, modern fonts, and a responsive layout.
- [x] Added social media icons for Facebook, Instagram, LinkedIn, and X (formerly Twitter), each linking to the relevant profiles.
- [x] Ensured accessibility improvements by increasing contrast and using semantic HTML elements for better usability.
- [x] Wrapped the `LocationOn`, `LocalPhone`, and `Email` icons in clickable links (Google Maps, phone dialer, and email client respectively).

## Checklist

- [x] I have tested my code, and it works as expected.
- [x] I have updated documentation to reflect these changes where necessary.
- [ ] I have included tests for the footer functionality.
- [x] I have followed the project's coding standards.

## Screenshots

image

### CODE REVIEW

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia  can you review the pr and assign it and add labels andlike gssoc-ext and also "level3" as th eissue was level3
issue: #14

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia can you also assign the correct label to myh other pr #9 
and #26 
and please assign label as "level3" 
not "level-3" as this doesnt work to get points

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia please change my other labels also

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia please change my other pr labels which i mentioned and also assign them i am waiting from 1 week but i dont hae a responce from you i am not getting any pioints from the prs i submitted to this project

Done!, 

let me know if you need any other help. I am reviewing this PR. 

Also please share the screenshot on mobile, tablet, and desktop views.

**Comment by Rizvi-Faiz** [comment]
## Phone:
image

## Tablet:
image

## Desktop:
image

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia  i have shared the screenshots please review it and merge it 
Thank you for Resolving the issues with the PRs

**Comment by Rizvi-Faiz** [comment]
Add labels and like gssoc-ext and also "level3" as the issue was level3
issue: #14

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia  ??

**Comment by saurabhbakolia** [comment]
Hey @Rizvi-Faiz, 
can you resolve the conflicts?

**Comment by Rizvi-Faiz** [comment]
> Hey @Rizvi-Faiz, can you resolve the conflicts?

i am unable to resolve

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia can you add the labels and assign it to me
Issue was #14 
it was level3 
please gssoc-ext

**Pull request merged**
