### PR TITLE
Added the filtering of products based on category #42 Seperating products based on category.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# Pull Request Template

Added the filtering of products based on category #42 Seperating products based on category.

## Description

I have properly done the seperation of products based on category and add filtering too so you can check it out and merge it.

## Related Issue

#42 Seperating products based on category.

## Changes Made

I have maded changes in ProductGallery.jsx and data.js in productGallery i have added filter and functioning of seperating and in data.js added the category to each of the product and also created a new list of categories used to create the filter.

## Checklist

- [X ] I have tested my code and it works as expected.
- [ X] I have added/updated documentation where necessary.
- [ X] I have included tests for new features.
- [ X] I have followed the project's coding standards.

## Screenshots (if applicable)

image
image

@thakuratul2 @saurabhbakolia Check this PR and merge it then assign this to me and put relvent labels like gssoc 2024 ext and hacktoberfest and level.

### CODE REVIEW

**Comment by tarunkumar2005** [comment]
@thakuratul2 @saurabhbakolia Can you review and merge it soon its been so many days since it is open

**Comment by thakuratul2** [comment]
@saurabhbakolia merge this code i done with the review

**Comment by tarunkumar2005** [comment]
@thakuratul2 @saurabhbakolia Still it is pending. Reminding you ....

**Comment by thakuratul2** [comment]
@tarunkumar2005 buddy please wait na

**Comment by tarunkumar2005** [comment]
> @tarunkumar2005 buddy please wait na

I was told if the PR is not merged you need to remind the Project mentor and admin everyday so that they don't forget about it in lot of traffic that's why. @thakuratul2

**Comment by thakuratul2** [comment]
@tarunkumar2005 i know buddy i already told to the project admin

**Comment by tarunkumar2005** [comment]
@thakuratul2 and @saurabhbakolia Why are you just not merging mine everyday there is a new conflict in this PR because you are merging others PR before mine it is been open for so long before also it was open for a week i think can you please merge this if you are done with the review i think you are done with the review @thakuratul2 but i don't see @saurabhbakolia is giving any response to this didn't merged it since then if you have found any issue then you can tell me i will solve but no response and no action on the PR shouldn't be there. I am sorry for this all but it is open for so long i can't everyday come and check okay there is a new conflict on this let me resolve this then they will merge then they will merge and so.

**Comment by tarunkumar2005** [comment]
@saurabhbakolia and @thakuratul2 Pending PR (reminder) its been a week.

**Comment by thakuratul2** [comment]
@saurabhbakolia please review it

**Comment by tarunkumar2005** [comment]
@thakuratul2 Just asking can't i trigger this reivew 

image

You have triggered just now

**Comment by thakuratul2** [comment]
@tarunkumar2005 i already message

**Comment by tarunkumar2005** [comment]
@thakuratul2 No bro i was asking like if i have access to trigger this review thing from a person like from admin or mentor but i think i don't have as a contributor. just asking that no  worries i was just reminding you. Take it easy

**Comment by thakuratul2** [comment]
@tarunkumar2005 oky

**Comment by MastanSayyad** [comment]
@saurabhbakolia Your mentor has told you so many times to respond, why are you not responding yet? I have also seen that you didn't added hacktoberfest  topic in your PR yet, or at least allow atul to merge these PRs, @thakuratul2 I saw you are working really hard here, if you want to switch the project then let me know, I'll assign new one to you

**Comment by tarunkumar2005** [comment]
@thakuratul2 @saurabhbakolia What is this i didn't even made changes to these many files according to this PR why it is conflicting in these many files ??? 
image

may i know why it is happning.

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia Your mentor has told you so many times to respond, why are you not responding yet? I have also seen that you didn't added hacktoberfest topic in your PR yet, or at least allow atul to merge these PRs, @thakuratul2 I saw you are working really hard here, if you want to switch the project then let me know, I'll assign new one to you


Hey @MastanSayyad, 
I am trying my best to reply everyone, and for `this you didn't add `hacktoberfest `topic in your PR yet`, I don't know what you are trying to say. 

I permitted @thakuratul2  before, but I saw too many bad merges. @MastanSayyad, How many mentors have you assigned for this project?

**Comment by saurabhbakolia** [comment]
> @thakuratul2 @saurabhbakolia What is this i didn't even made changes to these many files according to this PR why it is conflicting in these many files ??? image
> 
> may i know why it is happning.

Hey @tarunkumar2005, 
Just relax. I can see you're eager to contribute more to this repo, and that's great! That's why I added `Husky `support to format the files with each commit.

Also, please adjust your tone—everyone is doing their part. There's no need to keep reminding us, okay?

**Comment by tarunkumar2005** [comment]
> > @thakuratul2 @saurabhbakolia What is this i didn't even made changes to these many files according to this PR why it is conflicting in these many files ??? image
> > may i know why it is happning.
> 
> Hey @tarunkumar2005, Just relax. I can see you're eager to contribute more to this repo, and that's great! That's why I added `Husky `support to format the files with each commit.
> 
> Also, please adjust your tone—everyone is doing their part. There's no need to keep reminding us, okay?

I didn't said anything to you, i was just putting a reminder every two days as said by the sanjay sir and @MastanSayyad right keep reminding the PAs and mentors so that your message doesn't go unseen in much traffic that's why and about tone i have said nothing to you, then how you know what is my tone, you can check whole PR if i said anything to you which might have hurt your feelings or anything bad about you. and i was just asking why there are so many conflicting files is this bad tone?

**Comment by tarunkumar2005** [comment]
@saurabhbakolia Even when you are not actively viewing the PRs i didn't said anything i don't want to get involved in this i am just avoiding and thats why didn't raised any new issues if you are not actively particapiting then what will i do by raising issues it is just waste of time. So if you can merge this PR i will not raise new issues in your repo as i have seen how much you are actively contributing to the community and don't say these things when i have done nothing.

**Comment by saurabhbakolia** [comment]
> . So if you can merge this PR i will not raise new issues in your repo as

Thank you for informing me. I was a bit busy last week, but I have now added the relevant tags to the issues and PRs. I'll make sure to merge all open PRs and address any concerns promptly. I'll also check out the PA announcements on Discord.

Thanks for your understanding!

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia Even when you are not actively viewing the PRs i didn't said anything i don't want to get involved in this i am just avoiding and thats why didn't raised any new issues if you are not actively particapiting then what will i do by raising issues it is just waste of time. So if you can merge this PR i will not raise new issues in your repo as i have seen how much you are actively contributing to the community and don't say these things when i have done nothing.

Hey @tarunkumar2005, I see that this PR has some meaningful code, but it won’t work as intended right now. Would you prefer I close it, or Will you wait for some days until I try to adjust the issue? Either option is fine with me.

I’m currently working on refining the repository and improving the code styling to ensure that contributors don’t submit random code. I hope you understand.

**Comment by tarunkumar2005** [comment]
@saurabhbakolia You can do whatever you want i submitted it 10 days ago i think still it is same and that time also it was same, i don't want to mess around for just 10 points if you want the code merge it, don't want it close it do whatever its in your hand, i can't fix anything in this now if you want this merge it otherwise close it or discard it even though it is just of 10 points you made me worry about it for 10 days don't wanna work on this now anyhow so do whatever you feel right.

**Comment by saurabhbakolia** [comment]
Hey @tarunkumar2005, 

Closing this PR, as this feature is not required for now!

Thanks.

**Comment by tarunkumar2005** [comment]
@saurabhbakolia Very much thank you for your kind information, saying this is not required after assigning this issue to me and then after 10 days of creating the PR now you are saying you get 0 points because this is not required. Thank you again. What is this @MastanSayyad is this open source according to you, i am fond of these types of PAs 4-5 days before also some PA was saying same thing then you said both are in fault now what did i do in this it is just 10 points PR and he wasted my 10 days on this, first of all creating this and then resolving the conflicts, if he gives level3 for this then also it is not enough, i am frustrated with these types of things, why you include these types of PAs who doesn't want to work or wants contribution, i will post this on linkedin about this twice and thrice i have got same response when i am not in fault.

**Comment by sanjay-kv** [comment]
> > @tarunkumar2005 buddy please wait na
> 
> I was told if the PR is not merged you need to remind the Project mentor and admin everyday so that they don't forget about it in lot of traffic that's why. @thakuratul2

No one the core team made this suggestion to remind them everyday by tagging. 
instead I repeatedly mentioned to you opensource is wait game , 2 weeks or more is usually when comes to merging. 
If the PR is not yet merged until the 30th oct, core team will give you google form to add your PR and claim your points. 

@tarunkumar2005 
image
this ain't a right way to speak in public platform. 

Everyone is doing their job and admin has mentioned you why there is delay.

**Comment by sanjay-kv** [comment]
@tarunkumar2005 

https://youtu.be/TIzrPn1AnYo?si=wG2e6h552JW3y5Tp

I have already created to video on how to find active projects. 
be polite, have some patience, if you don't believe in us, try to contribute to any big public opensource project. 

https://github.com/apache/airflow

look how many PR and issue and wait time on single PR.

**Comment by tarunkumar2005** [comment]
@sanjay-kv I don't have issue with the team or so i have issue with the project admins like this not replying for so long then saying it is not needed or it is done by someone else now but if you are saying that i don't need to mention them, remind them or just submit the PR and forget about it then its fine i can do that no worries, i am a bit impatient i think so sorry for that i will keep this in mind.

**Comment by GSS0C24** [comment]
@saurabhbakolia 

try to give some explanation in future why its not required or use automated bot for issue and PR. 
This is also create issues between contributors. eventually less people contribute towards the project. 
image
If the above all CR is assigned issues then its concerning.

**Pull request closed without merging**
