### PR TITLE
issue:#41 Added eye icon to  login password field

### PR DESCRIPTION
**Pull request by AyushSharma72**
# Pull Request Template

 **Added eye icon to  login password field**

## Description

i just added eye icon to the login page password field

## Screenshots (if applicable)

Screenshot 2024-10-02 144611

Screenshot 2024-10-02 144604

please merge if you think its fine @saurabhbakolia

### CODE REVIEW

**Review by thakuratul2 — CHANGES_REQUESTED** [review]
@AyushSharma72 your code have some issues to deploy the website

**Comment by AyushSharma72** [comment]
> @AyushSharma72 your code have some issues to deploy the website
@saurabhbakolia how do know what is the error please share screenshot or something which helps me to know the error

**Comment by AyushSharma72** [comment]
> > @AyushSharma72 your code have some issues to deploy the website
> > @saurabhbakolia how do know what is the error please share screenshot or something which helps me to know the error

I cannot inspect it on vercel I am not authorised

**Comment by thakuratul2** [comment]
@AyushSharma72 you can see on your pr request

**Comment by thakuratul2** [comment]
image

@AyushSharma72 see

**Comment by saurabhbakolia** [comment]
@AyushSharma72 
Hey, 
why you are trying to merge directly into the master, instead push it to the develop branch?

**Comment by saurabhbakolia** [comment]
> @AyushSharma72 Hey, why you are trying to merge directly into the master, instead push it to the develop branch?

Create a new PR, and follow README.md file. 

closing this PR, ( as trying to merge directly into the master. )
Thanks.

**Comment by AyushSharma72** [comment]
> image
> 
> @AyushSharma72 see

I can see this but this is not what I was asking when you will go on vercel there it will show you what is exactly the error.

**Comment by AyushSharma72** [comment]
Any ways I will create another pr

**Pull request closed without merging**
