### PR TITLE
Updated footer

### LINKED ISSUE #14: Footer Improvement
# Footer Improvement

## Issue Overview

The current footer design lacks functionality and visual appeal, which can detract from the overall user experience. This section outlines suggested improvements for enhancing the footer.

## Current Limitations

- **Limited Information:** The footer currently contains minimal information, making it less informative for users.
- **Visual Design:** The design is outdated and does not align with modern UI standards, reducing engagement.
- **Accessibility Issues:** There may be issues with text contrast and clarity, affecting usability for all users.

### 1. Expand Footer Content
- **Description:** Include additional information such as links to privacy policies, terms of service, and contact information.
- **Expected Outcome:** Users have quick access to important information without navigating away from the page.

### 2. Modernize Visual Design
- **Description:** Update the footer’s visual elements, including colors, fonts, and layout, to align with current design trends.
- **Expected Outcome:** The footer should have a cohesive look that complements the overall application design.

### 3. Add Social Media Links
- **Description:** Include icons linking to the project's social media profiles (e.g., Twitter, Facebook, LinkedIn).
- **Expected Outcome:** Users can easily connect with the project on social media, increasing engagement and visibility.

### 4. Ensure Accessibility
- **Description:** Optimize the footer for accessibility by ensuring sufficient contrast and using semantic HTML elements.
- **Expected Outcome:** All users, including those with disabilities, can navigate the footer easily.

## Steps to Reproduce Current Issues

1. Open the application and scroll to the footer section.
2. Observe the limited information provided and assess the visual appeal.
3. Evaluate accessibility by checking color contrast and clarity.

## Screenshots

image
---

@thakuratul2 can you please assign this to me under gssoc-ext and hacktoberfest and also give a level

### PR DESCRIPTION
**Pull request by Rizvi-Faiz**
#**Title:** Improve footer design by adding content, modernizing design, and ensuring accessibility

## Description

This pull request enhances the footer by adding essential content such as Privacy Policy, Terms of Service, and Contact links. It also modernizes the visual design with updated colors, fonts, and a more user-friendly layout. Additionally, social media links have been added, and accessibility improvements, such as better contrast and semantic HTML structure, were made to ensure a more inclusive experience for all users.

## Related Issue

Fixes #14 

## Changes Made

- [x] Added Privacy Policy, Terms of Service, and Contact Us links.
- [x] Updated the visual design with improved color contrast and layout.
- [x] Added social media links for Facebook, Instagram, Twitter, and LinkedIn.
- [x] Enhanced accessibility by improving contrast and making the footer more keyboard-navigable.

## Checklist

- [x] I have tested my code and it works as expected.
- [x] I have added/updated documentation where necessary.
- [x] I have included tests for new features.
- [x] I have followed the project's coding standards.

### CODE REVIEW

**Comment by Rizvi-Faiz** [comment]
@thakuratul2  sir can you review it .

**Comment by thakuratul2** [comment]
@Rizvi-Faiz I am reviewing it meanwhile find new issue and fix it

**Comment by thakuratul2** [comment]
@Rizvi-Faiz check your branch having conflict so please fix it

**Review by thakuratul2 — COMMENTED** [review]
@Rizvi-Faiz Your request having conflicts please sove it

**Pull request closed without merging**
