### PR TITLE
Updated the read me file

### LINKED ISSUE #5: Add Pull Request MD file into README md
# Issue Report

## Title

Pull Request is missing from the ReadME md table of contents.

## Description

Could you add the pull request md into the README file and make the link clickable?

### PR DESCRIPTION
**Pull request by Rizvi-Faiz**
# Pull Request 

Title: Add Pull Request Section to README Table of Contents

## Description

This pull request adds a section in the README file for Pull Requests in the table of contents, making it easy for contributors to find and navigate to the relevant documentation. The link to the Pull Request documentation will be clickable for better accessibility.

## Related Issue

Fixes #5 

## Changes Made

- [ ] Added a "Pull Requests" section in the README table of contents.
- [ ] Made the link to the Pull Request documentation clickable.

## Checklist

- [ ] I have tested my code and it works as expected.
- [ ] I have added/updated documentation where necessary.
- [ ] I have included tests for new features.
- [ ] I have followed the project's coding standards.

## Screenshots 

Screenshot 2024-10-01 220241
Screenshot 2024-10-01 220545

---

### CODE REVIEW

**Comment by Rizvi-Faiz** [comment]
Sir I am not having an option to add a reviewers

image

**Review by thakuratul2 — APPROVED** [review]

**Comment by Rizvi-Faiz** [comment]
ok sir

**Comment by Rizvi-Faiz** [comment]
@thakuratul2 please add the levels in this pr and the gssoc-ext and hactoberfest
and also that you assigned me cause if you dont add they will not count towards my points
can you please add them

**Comment by saurabhbakolia** [comment]
> @thakuratul2 please add the levels in this pr and the gssoc-ext and hactoberfest and also that you assigned me cause if you dont add they will not count towards my points can you please add them

Done!

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia  the issue was level3 #7

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia SIRR CAN YOU PLEASE ADD THE LABELS TO THIS PR AND ALSO ASSIGN THIS PR TO ME AND THIS ISSUE IS LEVEL 3
SO PLEASE ADD THE LEVEL 3 LABEL AS I FIXED ISSUE NUMBER #5.
I AM NOT GETTING POINTS FOR THIS PR BECAUSE YOU DID NOT ASSIGN OR GIVE LABELS .
CAN YOU PLEASE DO IT.

**Comment by Rizvi-Faiz** [comment]
@saurabhbakolia  PLEASE UPDATE MY OTHER PR ALSO IN WHICH I MESSAGED YOU

**Comment by Rizvi-Faiz** [comment]
@saurabh it is "level3" not level-3
please add that 
AND MY OTHER PR IS #26  PLEASE ADD THE LABELS THER ALSO

**Pull request merged**
