### PR TITLE
Added FAQ and Contact us sections

### PR DESCRIPTION
**Pull request by govindumeesala**
# Pull Request Template

**Title:**Added contact us and faq sections to website

## Description

faq is added above newsletter 
and contact us is added below newsletter 
both responsive

## Related Issue

Fixes issue #84 

## Changes Made

added two components faq and contact us
- [x] Briefly describe the changes you made. Include any relevant information.

## Checklist

- [x] I have tested my code and it works as expected.
- [x] I have added/updated documentation where necessary.
- [x] I have included tests for new features.
- [x] I have followed the project's coding standards.

## Screenshots (if applicable)
image
image

@thakuratul2 @saurabhbakolia check this out please

### CODE REVIEW

**Review by saurabhbakolia — CHANGES_REQUESTED** [review]
Hey @govindumeesala,
I think it's cool, but what do you think about adding the FAQ section to the home page while having a separate page for `Contact Us`?

**Comment by govindumeesala** [comment]
> Hey @govindumeesala, I think it's cool, but what do you think about adding the FAQ section to the home page while having a separate page for `Contact Us`?

okay sure wil do it

**Comment by govindumeesala** [comment]
@saurabhbakolia  Heyy added separate contact us page to the site
Could you please consider adding level-2 to the issue, Only if you feel its worth.
image

**Comment by thakuratul2** [comment]
@govindumeesala your branch having conflicts fix asap

**Comment by govindumeesala** [comment]
> @govindumeesala your branch having conflicts fix asap

Heyy @thakuratul2 @saurabhbakolia I resolved the conflicts. Check once 
level label should be without dashes between them 

## remove level-1 and 
## add level1
## since they mentioned if dashes are added then not counted

**Comment by thakuratul2** [comment]
@saurabhbakolia review and merge if any issue not found

**Comment by govindumeesala** [comment]
@saurabhbakolia please check this out once

**Pull request closed without merging**
