### PR TITLE
Added automated greetings bot

### LINKED ISSUE #87: Add Automated Greeting Workflow
I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible .

Hey @thakuratul2 I can work on this.

### PR DESCRIPTION
**Pull request by harish08102004**
Fixed #87 

**Description**:
This pull request implements a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.

**Key Features**:
Automatic Greeting: Users will receive an immediate acknowledgment when they create an issue or pull request. The messages are:

**Implementation Details**:

Created a workflow file named greetings.yml in the .github/workflows directory.
Configured the workflow to trigger on both new issues and pull requests.
Utilized the actions/first-interaction action to manage the greeting messages.
This enhancement aims to foster a welcoming environment for contributors and improve community engagement.

### CODE REVIEW

**Comment by harish08102004** [comment]
Hey @saurabhbakolia please authorize it.

**Comment by saurabhbakolia** [comment]
> Hey @saurabhbakolia please authorize it.

Hey @harish08102004, 
Can you please create a PR for the `develop` branch?

**Comment by saurabhbakolia** [comment]
> > Hey @saurabhbakolia please authorize it.
> 
> Hey @harish08102004, Can you please create a PR for the `develop` branch?

And also how can I authorize, can you give me some idea?

**Comment by thakuratul2** [comment]
@harish08102004 i am closing this PR and please create the request to develop branch

**Comment by harish08102004** [comment]
ok

**Comment by harish08102004** [comment]
Hey @thakuratul2 I have raised the PR again to develop.
Please check and merge it.

**Pull request closed without merging**
