### PR TITLE
Passw recov

### PR DESCRIPTION
**Pull request by saras-69**
Description:
This pull request introduces the Password Recovery feature, allowing users to reset their passwords through a simple and user-friendly flow.

Related Issue
Fixes https://github.com/saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE/issues/201

Changes Made
Created the Password Recovery component with React.js.
Added a three-step flow:
Input email to simulate OTP sending.
Verify OTP.
Reset password.
Used alerts to simulate sending/verification of OTP and password reset.
Provided a basic structure for future backend integration.
Checklist
I have tested my code and it works as expected.
Documentation has been updated where necessary.
Tests for the new feature are included.
The code follows project standards.
Screenshots (if applicable)
(Include any relevant screenshots that illustrate your changes.)

https://github.com/user-attachments/assets/a26c4056-072f-4715-b9ed-062ee846e81b

Example:

Title: Password Recovery Feature
Description: Adds a password recovery feature with a simulated OTP flow.
Related Issue: Fixes https://github.com/saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE/issues/201
Changes Made:

Created components for password recovery.
Implemented a flow for email input, OTP verification, and password reset.
Added alerts to simulate OTP-related actions and password reset.

### CODE REVIEW

**Comment by saurabhbakolia** [comment]
Hey @saras-69, 

I noticed that you didn't share the screenshot of the UI. 
Please share it and describe the PR.

**Comment by saras-69** [comment]
@saurabhbakolia I already described in my first commit, if you  want I share it soon.

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia I already described in my first commit, if you want I share it soon.

Please share it here.

**Comment by saras-69** [comment]
> > @saurabhbakolia I already described in my first commit, if you want I share it soon.
> 
> Please share it here.



> > @saurabhbakolia I already described in my first commit, if you want I share it soon.
> 
> Please share it here.

Screenshot 2024-10-20 014214

**Comment by saras-69** [comment]
Hey @saurabhbakolia , I have submitted a pull request for the Password Recovery Feature, which enhances the app's usability and security by enabling users to securely reset forgotten passwords. The implementation required significant effort, including backend validation and front-end updates. I believe this aligns with the criteria for a Level 3 task, and I kindly request that this tag be assigned to the PR.

**Pull request merged**
