### PR TITLE
Add the cross button

### PR DESCRIPTION
**Pull request by hritika2409**
# Pull Request Template

**Title:** : Adding a close or a nav bar in Register and sign in option #170

## Description

Added the cross button so that one can go back

## Related Issue

Issue No: #170 

## Changes Made (ScreenShot/Video)

https://github.com/user-attachments/assets/15d796bc-34e4-4c01-a913-a506e865e9b1

## Checklist

- [x] I have tested my code and it works as expected.
- [x] I have added/updated documentation where necessary.
- [x] I have included tests for new features.
- [x] I have followed the project's coding standards.

### CODE REVIEW

**Comment by omkarkhot0500** [comment]
If your users might land on the login page directly (e.g., from an external source or bookmark) using navigate(-1) will cause some problem.

**Review by thakuratul2 — CHANGES_REQUESTED** [review]
@hritika2409 you need to create the PR request to develop branch not to master branch please do it

**Comment by hritika2409** [comment]
hey,Can you please reopen this issue i will work on this again.I am really very sorry .I was actually engage with some personal matter.I am sorry

**Comment by hritika2409** [comment]
@thakuratul2

**Pull request closed without merging**
