### PR TITLE
Added the filtering of products based on category #42 Seperating prod…

### PR DESCRIPTION
**Pull request by tarunkumar2005**
…ucts based on category.

# Pull Request Template

Added the filtering of products based on category #42 Seperating products based on category.

## Description

I have properly done the seperation of products based on category and add filtering too so you can check it out and merge it.

## Related Issue

#42 Seperating products based on category.

## Changes Made

I have maded changes in ProductGallery.jsx and data.js in productGallery i have added filter and functioning of seperating and in data.js added the category to each of the product and also created a new list of categories used to create the filter.

## Checklist

- [X ] I have tested my code and it works as expected.
- [ X] I have added/updated documentation where necessary.
- [ X] I have included tests for new features.
- [ X] I have followed the project's coding standards.

## Screenshots (if applicable)

image
image

---

### CODE REVIEW

**Comment by tarunkumar2005** [comment]
@saurabhbakolia Please review this request and merge it and add proper labels : gssoc 2024 ext, hacktoberfest, level 2 or level2 not level-2 okay and assign it to me.

**Comment by tarunkumar2005** [comment]
@thakuratul2 Can you check this PR and merge it.

**Comment by thakuratul2** [comment]
@tarunkumar2005 we can merge the code when you request will be correct i previously told that you need to create PR to develop

**Comment by tarunkumar2005** [comment]
> @tarunkumar2005 we can merge the code when you request will be correct i previously told that you need to create PR to develop

I can't understand what you want to say and you didn't said anything to me and if you have found any issue in this PR you can tell me i can fix that @thakuratul2

**Comment by thakuratul2** [comment]
@tarunkumar2005 you need to create the PR into develop branch not master branch

**Comment by tarunkumar2005** [comment]
> @tarunkumar2005 you need to create the PR into develop branch not master branch

This is my forked Repo not the original one. @thakuratul2

**Comment by tarunkumar2005** [comment]
image

**Comment by thakuratul2** [comment]
@tarunkumar2005 but you need to create the PR request into the develop branch not master branch

**Comment by tarunkumar2005** [comment]
okay so i will create a new PR then this can be closed.

**Pull request closed without merging**
