### PR TITLE
[Improvement] : Scroll To Top Button  #168

### PR DESCRIPTION
**Pull request by Amarjha01**
**Title:**
 Scroll To Top Button

## Description
Added scroll to top button on the right side to enhance user experience.

`Fixes: #168 `

## Changes Made

https://github.com/user-attachments/assets/aed67444-e61d-4756-8d45-0c7de9a0d862

- Added Button Scroll to the top from anywhere on the page.
- Fixed backend package.json warming.

## Checklist

- [X] I have tested my code and it works as expected.
- [X] I have followed the project's coding standards.

### CODE REVIEW

**Review by thakuratul2 — APPROVED** [review]
@Amarjha01 done

**Comment by thakuratul2** [comment]
@saurabhbakolia please review this

**Comment by Amarjha01** [comment]
@saurabhbakolia  1 more review is required to merge this PR please review this and merge it before this raises some conflict.

**Comment by thakuratul2** [comment]
@saurabhbakolia please review it

**Comment by saurabhbakolia** [comment]
Hey @Amarjha01,
Thanks for adding the BackToTop feature! However, I noticed that `Tailwind CSS` was used for styling. Could you please update it to use `Styled Components` instead? This will help maintain consistency with our coding style.

Thank you for your understanding!

**Comment by saurabhbakolia** [comment]
Hey @Amarjha01, 

can you create a new PR, as this pr contains too much unnecessary code?

Closing this PR.

**Pull request closed without merging**
